### ISSUE TITLE
Container isn't HTTPS aware

### ISSUE THREAD

**Issue by simonszu** [linuxserver/docker-freshrss#18]
The API for mobile clients isn't working when you are reverse-proxying an HTTPS endpoint into the container. First: The API-URL shown on my user profile is malformed: `https://rss.simonszu.de:80/p/api/` It doesn't matter if i map port 80 or 443 to the host and access the container internally via HTTP or HTTPS, the URL stays the same. 

Second: If i click on the API, it redirects me to a testing page with two links, like described [here](https://freshrss.github.io/FreshRSS/en/users/06_Mobile_access.html). However, if i click on any of these links, an endless loop of redirects is following which just adds a `/p` to the URL in each iteration, so the API is broken. 

I think this is because the container isn't aware that it is accessed via HTTPS.
	

Host-OS: Debian Stretch

Docker-Compose-File, slightly changed because i deploy the container with ansible:
```
- name: Start docker service
  docker_service:
    pull: yes
    project_name: freshrss
    definition:
      version: '2'
      services:
        app:
          restart: unless-stopped
          image: linuxserver/freshrss
          ports:
          - "9007:443"
          volumes:
          - "{{ docker_datadir }}/freshrss/app:/config"
          environment:
            PUID: 1000
            PGID: 1000
          depends_on:
          - db
        db:
          restart: unless-stopped
          image: mariadb
          environment:
            MYSQL_ROOT_PASSWORD: XXX
            MYSQL_USER: freshrss
            MYSQL_PASSWORD: XXX
            MYSQL_DATABASE: freshrss
          volumes:
          - "{{ docker_datadir }}/freshrss/db:/var/lib/mysql"
          networks:
          - default
      networks:
        default:
          external:
            name: backend
```

Docker log output:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    1000
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-config: executing...
[cont-init.d] 20-config: exited 0.
[cont-init.d] 30-keygen: executing...
using keys found in /config/keys
[cont-init.d] 30-keygen: exited 0.
[cont-init.d] 40-install: executing...
[cont-init.d] 40-install: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

No symlinks used.
