### ISSUE TITLE
Invalid tar magic - install fails

### ISSUE THREAD

**Issue by menteb** [linuxserver/docker-freshrss#32]
Docker refuses to install FreshRSS on initial launch.

## Docker-compose file

```
version: "3.2"
services:
  freshrss:
    image: linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Helsinki
    volumes:
      - /volume1/docker/freshrss/config:/config:rw
    ports:
      - 42080:80
      - 42443:443
    restart: unless-stopped
    networks:
      - net

networks:
  net:
    external: true
```

## Browser after install

`File not found.` 

## Log

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.,
[s6-init] ensuring user provided files have correct perms...exited 0.,
[fix-attrs.d] applying ownership & permissions fixes...,
[fix-attrs.d] done.,
[cont-init.d] executing container initialization scripts...,
[cont-init.d] 01-envfile: executing... ,
[cont-init.d] 01-envfile: exited 0.,
[cont-init.d] 10-adduser: executing... ,
,
-------------------------------------,
          _         (),
         | |  ___   _    __,
         | | / __| | |  /  \ ,
         | | \__ \ | | | () |,
         |_| |___/ |_|  \__/,
,
,
Brought to you by linuxserver.io,
We gratefully accept donations at:,
https://www.linuxserver.io/donate/,
-------------------------------------,
GID/UID,
-------------------------------------,
,
User uid:    1000,
User gid:    1000,
-------------------------------------,
,
[cont-init.d] 10-adduser: exited 0.,
[cont-init.d] 20-config: executing... ,
[cont-init.d] 20-config: exited 0.,
[cont-init.d] 30-keygen: executing... ,
using keys found in /config/keys,
[cont-init.d] 30-keygen: exited 0.,
[cont-init.d] 40-install: executing... ,
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current,
                                 Dload  Upload   Total   Spent    Left  Speed,

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100     9    0     9    0     0     30      0 --:--:-- --:--:-- --:--:--    30,
tar: invalid tar magic,
[cont-init.d] 40-install: exited 0.,
[cont-init.d] 99-custom-files: executing... ,
[custom-init] no custom files found exiting...,
[cont-init.d] 99-custom-files: exited 0.,
[cont-init.d] done.,
[services.d] starting services,
[services.d] done.,
```

## Environment
Docker: 18.09.8, build 2c0a67b
Linux: 4.4.59+ x86_64 GNU/Linux Synology 918+
